using System;
using System.Collections.Generic;
internal static class PointerFeelTests {
 static byte[] Report(int y,bool touched){var d=new byte[48];d[0]=0x45;Array.Copy(BitConverter.GetBytes(touched?0x02000000u:0u),0,d,2,4);Array.Copy(BitConverter.GetBytes((short)y),0,d,20,2);return d;}
 static int Wheel(List<string> a){int n=0;foreach(string s in a)if(s.StartsWith("Wheel delta="))n+=int.Parse(s.Substring(12));return n;}
 static void HardwareClickTest(){var b=new PadBook();using(var d=new DualPads(b)){var r=Report(0,true);Array.Copy(BitConverter.GetBytes(0x02200000u),0,r,2,4);d.Step(r,IntPtr.Zero,IntPtr.Zero,false);Array.Copy(BitConverter.GetBytes(0x02600000u),0,r,2,4);var a=d.Step(r,IntPtr.Zero,IntPtr.Zero,false);if(!a.Contains("LeftDown") || a.Contains("RightDown"))throw new Exception("Right hardware click lost or crossed pads");Array.Copy(BitConverter.GetBytes(0x02200000u),0,r,2,4);if(!d.Step(r,IntPtr.Zero,IntPtr.Zero,false).Contains("LeftUp"))throw new Exception("Hardware click release lost");Array.Copy(BitConverter.GetBytes(0x06200000u),0,r,2,4);if(!d.Step(r,IntPtr.Zero,IntPtr.Zero,false).Contains("RightDown"))throw new Exception("Left hardware click lost");}}
 internal static void Run(){HardwareClickTest();var b=new PadBook();b.Left.FineScroll=true;b.Left.ScrollUnits=6000;using(var d=new DualPads(b)){d.Step(Report(0,true),IntPtr.Zero,IntPtr.Zero,false);int sum=0;for(int i=1;i<=100;i++)sum+=Wheel(d.Step(Report(i*10,true),IntPtr.Zero,IntPtr.Zero,false));if(sum<19 || sum>20)throw new Exception("Fine scrolling lost fractional movement");if(Wheel(d.Step(Report(500,true),IntPtr.Zero,IntPtr.Zero,false))>=0)throw new Exception("Scroll reversal failed");d.Step(Report(0,false),IntPtr.Zero,IntPtr.Zero,false);if(Wheel(d.Step(Report(25000,true),IntPtr.Zero,IntPtr.Zero,false))!=0)throw new Exception("Retouch scroll jump");}
 b.Left.FineScroll=false;using(var d=new DualPads(b)){d.Step(Report(0,true),IntPtr.Zero,IntPtr.Zero,false);if(Wheel(d.Step(Report(1000,true),IntPtr.Zero,IntPtr.Zero,false))!=0)throw new Exception("Legacy scrolling changed");}
 var m=new MappingEngine(new DesktopSettings{Speed=.01125,SmoothMs=0,Inertia=false,DragScale=1,ClickStableMs=0});var r=Report(0,false);Array.Copy(BitConverter.GetBytes(0x200000u),0,r,2,4);m.StepAt(r,1);Array.Copy(BitConverter.GetBytes((short)800),0,r,24,2);if(!m.StepAt(r,1.01).Contains("Move dx=9 dy=0"))throw new Exception("Reference sensitivity mismatch");Array.Clear(r,2,4);if(m.StepAt(r,1.02).Exists(x=>x.StartsWith("Move")))throw new Exception("Direct pointer coasted after lift");Probe.Say("POINTER FEEL PASS: fine scroll, reversal, retouch, legacy scroll, direct sensitivity and lift.");}
}
