using System;
using System.Collections.Generic;
internal sealed class StickSources {
 double? last;double fx,fy;
 internal void Reset(){last=null;fx=fy=0;}
 static StickProfile Profile(PadBook b,int i){b.EnsureInputLayout();return i==0?b.LeftStick:b.RightStick;}
 static void Scaled(StickProfile p,byte[] raw,int i,out double x,out double y){x=BitConverter.ToInt16(raw,10+i*4)/32767.0;y=BitConverter.ToInt16(raw,12+i*4)/32767.0;double m=Math.Sqrt(x*x+y*y),dead=p.Deadzone/100.0,scale=m<=dead?0:Math.Min(1,(m-dead)/(1-dead))/m;x*=scale;y*=scale;}
 internal static ulong Directions(PadBook b,byte[] raw,ulong previous){ulong result=0;for(int i=0;i<2;i++){var p=Profile(b,i);if(p.Action!="wasd" && p.Action!="arrows" && p.Action!="directions")continue;int x=BitConverter.ToInt16(raw,10+i*4),y=BitConverter.ToInt16(raw,12+i*4);int[] v={y,-y,-x,x};for(int d=0;d<4;d++){ulong mask=1UL<<(40+i*4+d);double threshold=Math.Max(1,32767*p.Deadzone/100.0)*((previous&mask)!=0?.75:1);if(v[d]>threshold)result|=mask;}}return result;}
 internal static void Axes(PadBook b,byte[] raw,ref VirtualGamepad.Report r){for(int i=0;i<2;i++){var p=Profile(b,i);if(p.Action!="leftStick" && p.Action!="rightStick")continue;double x,y;Scaled(p,raw,i,out x,out y);if(p.Action=="leftStick"){r.LX=(short)Math.Round(x*32767);r.LY=(short)Math.Round(y*32767);}else{r.RX=(short)Math.Round(x*32767);r.RY=(short)Math.Round(y*32767);}}}
 internal List<string> Mouse(PadBook b,byte[] raw,double now){var a=new List<string>();double dt=last.HasValue?Math.Max(0,Math.Min(.05,(now-last.Value)/1000)):0;last=now;double mx=0,my=0;for(int i=0;i<2;i++){var p=Profile(b,i);if(p.Action!="mouse")continue;double x,y;Scaled(p,raw,i,out x,out y);mx+=x*p.Speed*dt;my-=y*p.Speed*dt;}fx=mx==0?0:fx+mx;fy=my==0?0:fy+my;int dx=(int)fx,dy=(int)fy;fx-=dx;fy-=dy;if(dx!=0 || dy!=0)a.Add("Move dx="+dx+" dy="+dy);return a;}
 internal static void Test(){var b=new PadBook{GamepadEnabled=true};b.Validate();var raw=new byte[48];raw[0]=0x45;Array.Copy(BitConverter.GetBytes((short)16000),0,raw,10,2);var r=VirtualGamepad.ConvertReport(b,raw,0);if(r.LX!=16000)throw new Exception("Legacy stick migration");b.LeftStick.Action="none";r=VirtualGamepad.ConvertReport(b,raw,0);if(r.LX!=0)throw new Exception("Disabled stick leaked");b.RightStick.Action="directions";Array.Copy(BitConverter.GetBytes((short)20000),0,raw,16,2);if((Directions(b,raw,0)&InputCatalog.SourceMask("RS_UP"))==0)throw new Exception("Right stick directions");b.LeftStick.Action="mouse";b.LeftStick.Speed=1000;Array.Copy(BitConverter.GetBytes((short)32767),0,raw,10,2);var s=new StickSources();s.Mouse(b,raw,0);if(!s.Mouse(b,raw,10).Contains("Move dx=10 dy=0"))throw new Exception("Stick mouse time scaling");s.Reset();if(s.Mouse(b,raw,1000).Count!=0)throw new Exception("Stick reset jump");b.Bindings.Clear();b.LeftStick.Action=b.RightStick.Action="none";if(b.NeedsVirtualGamepad)throw new Exception("Unused virtual output");b.Bindings["R4"]=new BindingAction{Kind="gamepad",Chord="A"};if(!b.NeedsVirtualGamepad)throw new Exception("Automatic virtual output");Probe.Say("STICK PASS: migration, disable, directions, mouse time scaling/reset, automatic virtual output.");}
}
