using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Web.Script.Serialization;
internal sealed partial class PadHop {
 TextBox BindingNumber(string text){return new TextBox{Text=text,Padding=new Thickness(9),Margin=new Thickness(0,0,14,8),Background=new SolidColorBrush(Color.FromRgb(17,29,40)),Foreground=Brushes.White,BorderBrush=new SolidColorBrush(Color.FromRgb(54,79,99)),BorderThickness=new Thickness(1)};}
 sealed class OutputOption{public string Key,Label;public override string ToString(){return Label;}}
 ComboBox BindingOutput(Panel parent,string kind,string value){if(kind=="keyboard")return KeyboardOutput(parent,value);var c=new ComboBox{MinWidth=160,Margin=new Thickness(0,4,0,8)};foreach(string key in kind=="mouse"?InputCatalog.Mouse:InputCatalog.Gamepad)c.Items.Add(new OutputOption{Label=kind=="mouse"?InputCatalog.MouseLabel(key):InputCatalog.ButtonLabel(key),Key=key});c.SelectedIndex=Math.Max(0,Array.IndexOf(kind=="mouse"?InputCatalog.Mouse:InputCatalog.Gamepad,value));parent.Children.Add(c);return c;}
 string BindingValue(ComboBox c){var field=c.Tag as TextBox;return field!=null?field.Text:((OutputOption)c.SelectedItem).Key;}
 Window CreateBindingDialog(string input,BindingAction initial){var json=new JavaScriptSerializer();var draft=json.Deserialize<BindingAction>(json.Serialize(initial));var dialog=new Window{Title=InputCatalog.ButtonLabel(input),Owner=window,Resources=window.Resources,Width=740,Height=Math.Min(720,SystemParameters.WorkArea.Height-60),MinWidth=620,MinHeight=400,WindowStartupLocation=WindowStartupLocation.CenterOwner,Background=new SolidColorBrush(Color.FromRgb(14,21,29)),Foreground=Brushes.White};var root=new DockPanel{Margin=new Thickness(22)};dialog.Content=root;var header=new StackPanel();DockPanel.SetDock(header,Dock.Top);root.Children.Add(header);header.Children.Add(new TextBlock{Text=InputCatalog.ButtonLabel(input),FontSize=22,FontWeight=FontWeights.SemiBold,Margin=new Thickness(0,0,0,16)});var types=new ComboBox{ItemsSource=new[]{"未设置","屏幕键盘 · 显示 / 隐藏","键盘与快捷键","鼠标","手柄输出","宏与连击"},Margin=new Thickness(0,0,0,14)};header.Children.Add(types);var footer=new StackPanel();DockPanel.SetDock(footer,Dock.Bottom);root.Children.Add(footer);var error=new TextBlock{Foreground=Brushes.Salmon,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,8,0,4)};footer.Children.Add(error);var buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};footer.Children.Add(buttons);Btn(buttons,"取消",delegate{dialog.Close();});var content=new StackPanel();root.Children.Add(new ScrollViewer{Content=content,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled});string[] kinds={"none","osk","keyboard","mouse","gamepad","macro"};Action read=delegate{};var cache=new Dictionary<string,BindingAction>();bool changing=false;Action render=null;render=delegate{content.Children.Clear();read=delegate{};if(draft.Kind=="none" || draft.Kind=="osk"){Hint(content,draft.Kind=="none"?"此输入不输出任何动作。手柄模式预设已为常规按键设置对应的手柄输出。":"按一次打开系统屏幕键盘，再按一次关闭。");return;}if(draft.Kind!="macro"){Hint(content,draft.Kind=="keyboard"?"选择按键，或输入组合键，例如 Win+D、Ctrl+Shift+S。":"选择输出动作");var output=BindingOutput(content,draft.Kind,draft.Chord);read=delegate{draft.Chord=BindingValue(output);};return;}
 var mode=Choice(content,"重复方式",new[]{"执行指定次数","按住持续连发，松开停止"});mode.SelectedIndex=draft.WhileHeld?1:0;var repeatRow=new StackPanel();content.Children.Add(repeatRow);Hint(repeatRow,"执行次数（1–100）");var repeat=BindingNumber(draft.Repeat.ToString());repeatRow.Children.Add(repeat);Action showRepeat=delegate{repeatRow.Visibility=mode.SelectedIndex==0?Visibility.Visible:Visibility.Collapsed;};mode.SelectionChanged+=delegate{showRepeat();};showRepeat();Hint(content,"按顺序执行；每一步先按住，再松开并等待。组合快捷键写在同一步中。");var steps=new StackPanel();content.Children.Add(steps);var readers=new List<Action>();Action flush=delegate{for(int i=0;i<readers.Count;i++)readers[i]();draft.WhileHeld=mode.SelectedIndex==1;draft.Repeat=draft.WhileHeld?1:int.Parse(repeat.Text);};for(int n=0;n<draft.Steps.Count;n++){int index=n;var step=draft.Steps[n];var body=new StackPanel{Margin=new Thickness(12)};steps.Children.Add(new Border{Child=body,Background=new SolidColorBrush(Color.FromRgb(28,43,56)),CornerRadius=new CornerRadius(6),Margin=new Thickness(0,0,0,10)});var top=Columns(body,2);Hint(Column(top,0),"步骤 "+(n+1));var order=Column(top,1);order.Orientation=Orientation.Horizontal;Btn(order,"↑",delegate{flush();if(index>0){draft.Steps.RemoveAt(index);draft.Steps.Insert(index-1,step);}render();});Btn(order,"↓",delegate{flush();if(index<draft.Steps.Count-1){draft.Steps.RemoveAt(index);draft.Steps.Insert(index+1,step);}render();});Btn(order,"删除",delegate{for(int j=0;j<readers.Count;j++)if(j!=index)readers[j]();draft.Steps.RemoveAt(index);render();});var row=Columns(body,2);var type=Choice(Column(row,0),"输出类型",new[]{"键盘 / 组合键","鼠标","手柄"});type.SelectedIndex=Array.IndexOf(new[]{"keyboard","mouse","gamepad"},step.Kind);var host=Column(row,1);Hint(host,"输出动作");var output=BindingOutput(host,step.Kind,step.Chord);type.SelectionChanged+=delegate{step.Kind=new[]{"keyboard","mouse","gamepad"}[type.SelectedIndex];host.Children.Clear();Hint(host,"输出动作");output=BindingOutput(host,step.Kind,step.Kind=="keyboard"?"Space":step.Kind=="mouse"?"left":"A");};var timing=Columns(body,2);var a=Column(timing,0);Hint(a,"按住时间 · ms");var hold=BindingNumber(step.HoldMs.ToString());a.Children.Add(hold);var b=Column(timing,1);Hint(b,"松开后等待 · ms");var wait=BindingNumber(step.WaitMs.ToString());b.Children.Add(wait);readers.Add(delegate{step.Chord=BindingValue(output);step.HoldMs=int.Parse(hold.Text);step.WaitMs=int.Parse(wait.Text);});}Btn(content,"＋ 添加步骤",delegate{flush();draft.Steps.Add(new MacroStroke());render();});read=flush;};
 Btn(buttons,"确定",delegate{try{read();draft.Validate();SetBinding(input,draft);dialog.Close();}catch(Exception ex){error.Text=ex.Message;}});types.SelectedIndex=Array.IndexOf(kinds,draft.Kind);render();types.SelectionChanged+=delegate{if(changing)return;string old=draft.Kind;try{read();cache[old]=draft;string next=kinds[types.SelectedIndex];if(!cache.TryGetValue(next,out draft)){draft=new BindingAction{Kind=next,Chord=next=="keyboard"?"Space":next=="mouse"?"left":"A"};if(next=="macro")draft.Steps.Add(new MacroStroke());}error.Text="";render();}catch(Exception ex){changing=true;types.SelectedIndex=Array.IndexOf(kinds,old);changing=false;error.Text=ex.Message;}};return dialog;}
 void TestBindingDialogs(){window.ShowInTaskbar=false;window.WindowStartupLocation=WindowStartupLocation.Manual;window.Left=-4000;window.Top=-4000;window.Show();foreach(string kind in new[]{"gamepad","mouse","keyboard","macro"}){var initial=new BindingAction{Kind=kind,Chord=kind=="keyboard"?"Win+D":kind=="mouse"?"right":"A"};if(kind=="macro")initial.Steps.Add(new MacroStroke{Kind="gamepad",Chord="A"});var d=CreateBindingDialog("L4",initial);d.ShowInTaskbar=false;d.WindowStartupLocation=WindowStartupLocation.Manual;d.Left=-4000;d.Top=-4000;d.Show();d.UpdateLayout();var combos=LogicalChildren(d).OfType<ComboBox>().ToArray();foreach(var c in combos.Skip(1)){c.IsDropDownOpen=true;d.UpdateLayout();if(c.Items.Count>1)c.SelectedIndex=1;d.UpdateLayout();c.IsDropDownOpen=false;}d.Close();}var legacy=new ComboBox();legacy.Items.Add(new ComboBoxItem{Content="A"});legacy.Items.Add(new ComboBoxItem{Content="B"});legacy.SelectedIndex=0;var sample=new Window{Resources=window.Resources,Content=legacy,Width=300,Height=150,ShowInTaskbar=false,Left=-4000,Top=-4000,WindowStartupLocation=WindowStartupLocation.Manual};sample.Show();legacy.IsDropDownOpen=true;sample.UpdateLayout();legacy.SelectedIndex=1;sample.UpdateLayout();legacy.IsDropDownOpen=false;sample.Close();window.Hide();}
 static IEnumerable<DependencyObject> LogicalChildren(DependencyObject parent){foreach(object item in LogicalTreeHelper.GetChildren(parent)){var child=item as DependencyObject;if(child==null)continue;yield return child;foreach(var descendant in LogicalChildren(child))yield return descendant;}}

}
