using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
internal static class IconMaker {
 static Bitmap Draw(int size){var b=new Bitmap(size,size,PixelFormat.Format32bppArgb);using(var g=Graphics.FromImage(b)){g.SmoothingMode=SmoothingMode.AntiAlias;g.ScaleTransform(size/128f,size/128f);using(var back=new SolidBrush(Color.FromArgb(15,25,36)))g.FillPolygon(back,new[]{new PointF(23,6),new PointF(105,6),new PointF(122,23),new PointF(122,105),new PointF(105,122),new PointF(23,122),new PointF(6,105),new PointF(6,23)});using(var p=new Pen(Color.FromArgb(72,191,242),8)){p.StartCap=p.EndCap=LineCap.Square;g.DrawLines(p,new[]{new PointF(34,33),new PointF(23,33),new PointF(23,95),new PointF(34,95)});g.DrawLines(p,new[]{new PointF(49,64),new PointF(76,64),new PointF(96,40)});g.DrawLines(p,new[]{new PointF(76,64),new PointF(96,88)});}using(var brush=new SolidBrush(Color.FromArgb(226,246,255)))g.FillPolygon(brush,new[]{new PointF(48,52),new PointF(60,64),new PointF(48,76),new PointF(36,64)});using(var mint=new SolidBrush(Color.FromArgb(89,229,188))){g.FillRectangle(mint,92,29,15,15);g.FillRectangle(mint,92,84,15,15);}}return b;}
 static int Main(string[] args){string dir=args[0];Directory.CreateDirectory(dir);using(var b=Draw(512))b.Save(Path.Combine(dir,"app.png"),ImageFormat.Png);int[] sizes={16,20,24,32,48,64,128,256};var blobs=new byte[sizes.Length][];for(int i=0;i<sizes.Length;i++)using(var b=Draw(sizes[i]))using(var ms=new MemoryStream()){b.Save(ms,ImageFormat.Png);blobs[i]=ms.ToArray();}using(var w=new BinaryWriter(File.Create(Path.Combine(dir,"app.ico")))){w.Write((ushort)0);w.Write((ushort)1);w.Write((ushort)sizes.Length);int offset=6+16*sizes.Length;for(int i=0;i<sizes.Length;i++){w.Write((byte)(sizes[i]==256?0:sizes[i]));w.Write((byte)(sizes[i]==256?0:sizes[i]));w.Write((byte)0);w.Write((byte)0);w.Write((ushort)1);w.Write((ushort)32);w.Write(blobs[i].Length);w.Write(offset);offset+=blobs[i].Length;}foreach(var blob in blobs)w.Write(blob);}return 0;}
}
