using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Interop;
using System.Windows.Threading;
internal sealed partial class PadHop {
 static string KeyLabel(string key){switch(key){case "Space":return L.T("空格 · Space");case "Enter":return L.T("回车 · Enter");case "Escape":return L.T("退出 · Escape");case "Backspace":return L.T("退格 · Backspace");case "Delete":return L.T("删除 · Delete");case "Up":return L.T("方向上 · Up");case "Down":return L.T("方向下 · Down");case "Left":return L.T("方向左 · Left");case "Right":return L.T("方向右 · Right");case "Win":return L.T("Windows 徽标键 · Win");case "Tab":return L.T("制表 / 切换 · Tab");default:return key;}}
 ComboBox KeyboardOutput(Panel parent,string value){var field=BindingNumber(value);field.ToolTip=L.T("可直接输入单键或组合键，例如 Win+D。");parent.Children.Add(field);var record=Btn(parent,L.T("录入按键"),delegate{});var status=Hint(parent,L.T("点击录入后按下按键或组合键，全部松开后结束。"));KeyboardRecorder recorder=null;Action stop=delegate{if(recorder!=null){recorder.Dispose();recorder=null;}record.Content=L.T("录入按键");};record.Click+=delegate{if(recorder!=null){stop();status.Text=L.T("已取消录入，保留原动作。");return;}try{recorder=new KeyboardRecorder(Window.GetWindow(record),delegate(string chord){field.Text=chord;status.Text=L.T("已录入：")+chord;stop();},delegate(string reason){stop();status.Text=reason;});record.Content=L.T("取消录入");status.Text=L.T("等待按键…全部松开后完成（15 秒内）。");}catch(Exception ex){stop();status.Text=ex.Message;}};record.Unloaded+=delegate{stop();};var search=BindingNumber("");search.ToolTip=L.T("搜索名称，例如 空格、Win、F1；留空显示常用键和全部按键。");Hint(parent,L.T("搜索 / 选择按键"));parent.Children.Add(search);var c=new ComboBox{Tag=field,MinWidth=160,Margin=new Thickness(0,4,0,8)};parent.Children.Add(c);var keys=new[]{"Space","Enter","Escape","Alt+Tab","Win+D","Win+E","Ctrl+C","Ctrl+V","Ctrl+Shift+S"}.Concat(InputCatalog.Keys.Keys).Distinct().Select(k=>new OutputOption{Key=k,Label=KeyLabel(k)}).ToList();bool filtering=false;Action filter=delegate{filtering=true;string q=search.Text.Trim();var matches=keys.Where(k=>k.Label.IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0).ToList();matches.Insert(0,new OutputOption{Label=matches.Count==0?L.T("没有匹配的按键"):L.T("选择按键…")});c.ItemsSource=matches;c.SelectedIndex=0;filtering=false;};search.TextChanged+=delegate{filter();c.IsDropDownOpen=true;};c.SelectionChanged+=delegate{if(!filtering && c.SelectedItem!=null && ((OutputOption)c.SelectedItem).Key!=null)field.Text=((OutputOption)c.SelectedItem).Key;};filter();return c;}
 sealed class KeyboardRecorder:IDisposable {
 delegate IntPtr Hook(int code,IntPtr message,IntPtr data);readonly Hook callback;IntPtr handle;readonly IntPtr owner;readonly Action<string> done,cancel;readonly DispatcherTimer timer;readonly HashSet<int> pressed=new HashSet<int>();readonly List<int> chord=new List<int>();bool completed;
 internal KeyboardRecorder(Window window,Action<string> done,Action<string> cancel){this.done=done;this.cancel=cancel;owner=new WindowInteropHelper(window).Handle;callback=Receive;handle=SetWindowsHookEx(13,callback,GetModuleHandle(null),0);if(handle==IntPtr.Zero)throw new Exception(L.T("无法开始按键录入：")+Marshal.GetLastWin32Error());timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(100)};DateTime end=DateTime.UtcNow.AddSeconds(15);timer.Tick+=delegate{if(GetForegroundWindow()!=owner || DateTime.UtcNow>end)Cancel(L.T("录入已结束，未修改原动作。"));};timer.Start();}
 IntPtr Receive(int code,IntPtr message,IntPtr data){if(code<0 || completed)return CallNextHookEx(handle,code,message,data);if(GetForegroundWindow()!=owner){Cancel(L.T("窗口已切换，取消录入。"));return CallNextHookEx(handle,code,message,data);}try{int vk=Marshal.ReadInt32(data);long msg=message.ToInt64();if(msg==0x100 || msg==0x104){pressed.Add(vk);if(!chord.Contains(vk))chord.Add(vk);}else if(msg==0x101 || msg==0x105){pressed.Remove(vk);if(pressed.Count==0 && chord.Count>0){string result=Chord(chord);completed=true;done(result);}}return new IntPtr(1);}catch(Exception ex){Cancel(ex.Message);return new IntPtr(1);}}
 internal static string Chord(IEnumerable<int> values){var names=new List<string>();foreach(int vk in values.OrderBy(k=>InputCatalog.IsModifier(k)?0:1)){var key=InputCatalog.Keys.FirstOrDefault(k=>k.Value==vk).Key;if(key==null)throw new Exception(L.T("暂不支持此按键（")+vk+L.T("），请搜索选择。 "));names.Add(key);}string result=string.Join("+",names);InputCatalog.Parse(result);return result;}
 void Cancel(string reason){if(completed)return;completed=true;Dispose();cancel(reason);}
 public void Dispose(){if(timer!=null)timer.Stop();if(handle!=IntPtr.Zero){UnhookWindowsHookEx(handle);handle=IntPtr.Zero;}completed=true;}
 [DllImport("user32.dll",SetLastError=true)]static extern IntPtr SetWindowsHookEx(int id,Hook hook,IntPtr module,uint thread);
 [DllImport("user32.dll")]static extern bool UnhookWindowsHookEx(IntPtr hook);
 [DllImport("user32.dll")]static extern IntPtr CallNextHookEx(IntPtr hook,int code,IntPtr message,IntPtr data);
 [DllImport("user32.dll")]static extern IntPtr GetForegroundWindow();
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode)]static extern IntPtr GetModuleHandle(string name);
 }
}
