using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
internal sealed partial class PadHop {
 readonly ComboBox[] stickActions=new ComboBox[2];readonly TextBox[] stickDeadzone=new TextBox[2],stickSpeed=new TextBox[2];readonly StackPanel[] stickDirections=new StackPanel[2],stickSpeedRows=new StackPanel[2],stickDeadzoneRows=new StackPanel[2];readonly Button[] stickPress=new Button[2];readonly Dictionary<string,Button>[] stickDirectionButtons={new Dictionary<string,Button>(),new Dictionary<string,Button>()};bool loadingSticks;
 static readonly string[] StickActions={"none","leftStick","rightStick","wasd","arrows","directions","mouse"};
 StickProfile Stick(int i){padBook.EnsureInputLayout();return i==0?padBook.LeftStick:padBook.RightStick;}
 void BuildStickEditor(TabControl tabs){var body=new StackPanel{Margin=new Thickness(0,12,0,0)};tabs.Items.Add(new TabItem{Header="摇杆",Content=body});var grid=Columns(body,2);for(int n=0;n<2;n++){int i=n;var p=Column(grid,i);stickActions[i]=Choice(p,i==0?"左摇杆 · 推动动作":"右摇杆 · 推动动作",new[]{"不映射","输出左摇杆","输出右摇杆","WASD","方向键 ↑ ↓ ← →","自定义四方向","移动鼠标"});stickPress[i]=Btn(p,"",delegate{EditBinding(i==0?"L3":"R3");});stickDirections[i]=new StackPanel();p.Children.Add(stickDirections[i]);foreach(string d in new[]{"UP","DOWN","LEFT","RIGHT"}){string dir=d;stickDirectionButtons[i][dir]=Btn(stickDirections[i],d,delegate{EditBinding((i==0?"LS_":"RS_")+dir);});}stickDeadzoneRows[i]=new StackPanel();p.Children.Add(stickDeadzoneRows[i]);Hint(stickDeadzoneRows[i],"中心死区 % · 越大越不容易误触");stickDeadzone[i]=SliderNumber(stickDeadzoneRows[i],0,80,1);stickSpeedRows[i]=new StackPanel();p.Children.Add(stickSpeedRows[i]);Hint(stickSpeedRows[i],"鼠标速度 · 满推时 px/s");stickSpeed[i]=SliderNumber(stickSpeedRows[i],50,3000,50);stickDeadzone[i].TextChanged+=delegate{int value;if(!loadingSticks && int.TryParse(stickDeadzone[i].Text,out value) && value>=0 && value<=80){Stick(i).Deadzone=value;UpdateFullStatus();}};stickSpeed[i].TextChanged+=delegate{double value;if(!loadingSticks && double.TryParse(stickSpeed[i].Text,out value) && value>=50 && value<=3000){Stick(i).Speed=value;UpdateFullStatus();}};stickActions[i].SelectionChanged+=delegate{if(loadingSticks || stickActions[i].SelectedIndex<0)return;var current=Stick(i);string next=StickActions[stickActions[i].SelectedIndex];if(next=="directions" && (current.Action=="wasd" || current.Action=="arrows"))current.Directions=current.Bindings();current.Action=next;SyncButtons();UpdateFullStatus();};}Hint(body,"WASD 和方向键会在摇杆回中时释放。按下摇杆的动作可独立设置，和整份配置一起试用、应用或保存。");SyncSticks();}
 void SyncSticks(){if(stickActions[0]==null)return;loadingSticks=true;try{for(int i=0;i<2;i++){var p=Stick(i);stickActions[i].SelectedIndex=Array.IndexOf(StickActions,p.Action);stickDeadzone[i].Text=p.Deadzone.ToString();stickSpeed[i].Text=p.Speed.ToString(System.Globalization.CultureInfo.InvariantCulture);stickPress[i].Content=(i==0?"L3":"R3")+" · 按下："+GetBinding(i==0?"L3":"R3");stickDirections[i].Visibility=p.Action=="directions"?Visibility.Visible:Visibility.Collapsed;stickDeadzoneRows[i].Visibility=p.Action=="none"?Visibility.Collapsed:Visibility.Visible;stickSpeedRows[i].Visibility=p.Action=="mouse"?Visibility.Visible:Visibility.Collapsed;foreach(var row in stickDirectionButtons[i])row.Value.Content=InputCatalog.ButtonLabel(row.Key)+" · "+p.Directions[row.Key];}}finally{loadingSticks=false;}}
 void ReadSticks(){if(stickActions[0]==null)return;for(int i=0;i<2;i++){var p=Stick(i);p.Deadzone=int.Parse(stickDeadzone[i].Text);p.Speed=double.Parse(stickSpeed[i].Text,System.Globalization.CultureInfo.InvariantCulture);p.Validate();}}
 void TestStickEditor(){padBook=StarterPreset("keyboard");LoadPad();if(stickActions[0].SelectedIndex!=3 || virtualOutputBox.IsChecked==true)throw new Exception("Keyboard preset stick UI");stickActions[1].SelectedIndex=5;SetBinding("RS_UP",new BindingAction{Kind="keyboard",Chord="E"});stickDeadzone[1].Text="30";ReadEditor();var saved=Clone(padBook);if(saved.RightStick.Action!="directions" || saved.RightStick.Deadzone!=30 || saved.EffectiveBindings()["RS_UP"].Chord!="E" || saved.LeftStick.Action!="wasd")throw new Exception("Independent stick persistence");padBook=StarterPreset("gamepad");LoadPad();if(virtualOutputBox.IsChecked!=true)throw new Exception("Gamepad preset virtual output");virtualOutputBox.IsChecked=false;ReadEditor();if(Clone(padBook).VirtualOutputEnabled)throw new Exception("Virtual output off not saved");}

}
